# Generated by Django 5.0 on 2024-01-18 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEcommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
