# Generated by Django 5.0 on 2024-01-19 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEcommerce', '0003_remove_productos_id_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='marca',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AppEcommerce.productosmarcas'),
            preserve_default=False,
        ),
    ]
