# Generated by Django 5.0 on 2024-01-20 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEcommerce', '0005_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductosEvaluaciones',
        ),
        migrations.DeleteModel(
            name='ProductosEvaluacionesEstados',
        ),
        migrations.DeleteModel(
            name='ProductosImagenes',
        ),
        migrations.DeleteModel(
            name='ProductosTalles',
        ),
        migrations.DeleteModel(
            name='ProductosTallesDiponibles',
        ),
        migrations.AddField(
            model_name='productos',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_productos/'),
        ),
    ]
